[package]
name = "runtime"
version = "0.4.5"
edition = "2021"
license.workspace = true

[package.metadata.android]
package = "dev.tileline.runtime"
build_targets = ["aarch64-linux-android"]
min_sdk_version = 29
target_sdk_version = 34

[features]
default = ["gamepad", "parallel_pipeline_v2"]
gamepad = ["dep:gilrs"]
parallel_pipeline_v2 = []
sxrc-compression = ["mps/sxrc-compression"]

[dependencies]
tl-core = { path = "../tl-core" }
wgpu.workspace = true
mps = { path = "../mps" }
paradoxpe = { git = "https://github.com/berrycomp/paradoxpe" }
gms = { git = "https://github.com/berrycomp/gms" }
tokio = { workspace = true, features = ["net", "time", "rt", "macros"] }
nalgebra.workspace = true
num_cpus.workspace = true
crossbeam.workspace = true
notify = "6.1.1"
bytemuck = { version = "1.17.1", features = ["derive"] }
winit.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
fbx = "0.2.0"
pollster = "0.4.0"
gilrs = { version = "0.11.0", optional = true }
font8x8 = "0.3.1"
regex = "1.11.1"
hound = "3.5.1"
image = { version = "0.25.5", default-features = false, features = ["png"] }
resvg = { version = "0.45.1", default-features = true }

[target.'cfg(target_os = "macos")'.dependencies]
metal = "0.33.0"

[dev-dependencies]
